// ============================================================
// telegramAgent.js — AviSignals Telegram Agent v2
//
// Three jobs in one file:
//  1. CHANNEL BROADCASTER  — posts 3x per hour to the public
//     channel with rotating content (sales pitch, success story,
//     signal tease, urgency post, educational, testimonial)
//  2. ADMIN BOT            — answers your questions about the
//     business in real-time via Telegram private chat
//  3. SOCIAL MEDIA SYNC    — shares the daily content calendar
//     generated by socialMediaAgent directly to admin
//
// Improvements over v1:
//  - 3x per hour (was once every 3 hours)
//  - 6 rotating content types — never repeats same format twice in a row
//  - Post history fed back to AI so it never repeats content
//  - Admin bot with polling — you can message it any question
//  - Admin bot has full business context + live Supabase data
//  - Proper byte-length Content-Length (fixes Unicode bugs)
//  - Retry logic on Telegram API failures
//  - Clean HTML formatting for channel posts
// ============================================================

'use strict';

const cron = require('node-cron');
const https = require('https');
const groq = require('./groqClient');
const { createClient } = require('@supabase/supabase-js');
const { translateToAgent } = require('../marketing/translator');

const supabase = createClient(
    (process.env.SUPABASE_URL || '').trim().replace(/\/+$/, ''),
    (process.env.SUPABASE_SERVICE_ROLE_KEY || '').trim()
);

// ─── Config ───────────────────────────────────────────────────
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const CHANNEL_ID = process.env.TELEGRAM_CHANNEL_ID || '@AviSignalsAviatorPredictorBot';
const ADMIN_CHAT = process.env.TELEGRAM_CHAT_ID;    // your personal Telegram chat ID
const SITE_URL = 'https://avisignals.com';
const BOT_URL = `${SITE_URL}/bot`;

// ─── Post history (in-memory, last 10 posts) ─────────────────
// Prevents repeating the same content
const postHistory = [];
const MAX_HISTORY = 10;

function addToHistory(type, preview) {
    postHistory.push({ type, preview: preview.slice(0, 80), at: new Date().toLocaleTimeString() });
    if (postHistory.length > MAX_HISTORY) postHistory.shift();
}

// ─── Content type rotation ────────────────────────────────────
const CONTENT_TYPES = [
    'sales_pitch',
    'success_story',
    'signal_tease',
    'urgency',
    'educational',
    'testimonial'
];
let contentTypeIndex = 0;

function nextContentType() {
    const type = CONTENT_TYPES[contentTypeIndex % CONTENT_TYPES.length];
    contentTypeIndex++;
    return type;
}

// ============================================================
// TEMPLATE CONTENT GENERATORS — AI-FREE, zero Groq tokens
// Same 6 content types, powered by rotating pre-written pools.
// ============================================================

function pickRandom(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

const SALES_PITCH_POOL = [
    `🚀 *Don't guess. Predict.*\n\nAviSignals uses real-time AI analysis to tell you when to cash out — before the round ends.\n\n🆓 Start your Free Trial session to see how it works: ${BOT_URL}\n💎 Want full 24H access? Just $75. No subscriptions.`,
    `🎯 *Your edge in Aviator starts here.*\n\n3,200+ members are using AviSignals daily to time their cash-outs with precision.\n\n🆓 Test the bot with our Free Trial — no payment needed to start.\n👉 ${BOT_URL}`,
    `⚡ *The smart way to play Aviator.*\n\nOur AI reads the game — follow the signal and cash out at the right moment.\n\n✅ Free trial available right now to test accuracy.\n🔗 ${BOT_URL}`,
    `🔥 *Stop losing. Start predicting.*\n\nAviSignals gives you data-driven signals for every Aviator round.\n\n🆓 Try the free trial to train before buying a code:\n📲 ${BOT_URL}`,
    `💡 *What if you knew when to cash out?*\n\nThat's exactly what AviSignals does. AI-powered round analysis. Real-time signals.\n\n🎁 Start your free trial session: ${BOT_URL}`,
];

const SUCCESS_STORIES = [
    { name: 'James M.', city: 'Sydney', start: 'AUD 8,000', end: 'AUD 150,000', site: '1xBet', days: 2 },
    { name: 'Grace W.', city: 'Mombasa', start: 'KES 5,000', end: 'KES 162,000', site: 'Betika', days: 1 },
    { name: 'Brian O.', city: 'Cape Town', start: 'R 3,000', end: 'R 41,000', site: 'Betway', days: 1 },
    { name: 'Amara K.', city: 'Kampala', start: 'UGX 50,000', end: 'UGX 1,900,000', site: 'Bangbet', days: 3 },
    { name: 'David N.', city: 'London', start: 'GBP 1,000', end: 'GBP 75,000', site: '1win', days: 2 },
    { name: 'Fatima H.', city: 'Dar es Salaam', start: 'TZS 20,000', end: 'TZS 880,000', site: 'Parimatch', days: 1 },
    { name: 'Collin P.', city: 'Romania', start: 'EUR 200', end: 'EUR 32,000', site: '1win', days: 2 },
    { name: 'Jefar A.', city: 'Dubai', start: 'AED 8,000', end: 'AED 150,000', site: '1xBet', days: 2 },
];
let storyIndex = 0;

function generateSalesPitch() {
    return { choices: [{ message: { content: pickRandom(SALES_PITCH_POOL) } }] };
}

function generateSuccessStory() {
    const s = SUCCESS_STORIES[storyIndex % SUCCESS_STORIES.length];
    storyIndex++;
    const text = `🏆 *Real member. Real results.*\n\n_"I started with ${s.start} on ${s.site}. After ${s.days} day(s) using AviSignals, I walked away with ${s.end}."_\n— *${s.name}*, ${s.city}\n\n🚀 Start your own story — try the free trial to see it work: ${BOT_URL}`;
    return { choices: [{ message: { content: text } }] };
}

function generateSignalTease() {
    const multipliers = ['7.4x', '12.1x', '3.8x', '18.6x', '5.2x', '9.9x', '22.4x', '35.2x', '16.1x'];
    const multi = pickRandom(multipliers);
    const text = `📡 *Signal confirmed: ${multi}*\n\nOur bot called it. Members who followed the signal cashed out at exactly the right moment. 🎯\n\n🆓 Try the free trial to see it in action:\n👉 ${BOT_URL}`;
    return { choices: [{ message: { content: text } }] };
}

function generateUrgencyPost() {
    const hour = new Date().getHours();
    const session = hour < 12 ? 'morning session' : hour < 18 ? 'afternoon session' : "tonight's session";
    const text = `⏰ *The ${session} is LIVE right now.*\n\nMembers are already using their codes. Don't miss today's rounds.\n\n🆓 Try the free trial session to test accuracy.\n💎 Want 24H access? Get a premium code for $75.\n\n👉 ${BOT_URL}`;
    return { choices: [{ message: { content: text } }] };
}

function generateEducationalPost() {
    const tips = [
        `📌 *Pro Tip: Cash out early on high-volatility rounds.*\n\nWhen the AviSignals bot shows a low confidence score, take your profit at 1.5x or 2x instead of pushing for 10x. Consistency beats luck.\n\n💡 Get the bot: ${BOT_URL}`,
        `📌 *Free Trial vs Premium Code — what's the difference?*\n\n🆓 Free trial: 60-minute test session on assigned random trial site.\n💎 Premium code: Full 24H access, any site worldwide.\n\nTest and see how it works, then buy a code for the site you want!\n👉 ${BOT_URL}`,
        `📌 *Timing your bet matters more than bet size.*\n\nA $10 bet at the right moment beats a $100 bet at the wrong one. AviSignals tells you exactly when to enter and when to hold off.\n\n🔗 ${BOT_URL}`,
        `💡 *How to use AviSignals and play at the same time:*\n\n1. Open the bot on your phone\n2. Open your betting site on the same device or another\n3. Follow the signal — cash out when the bot says GO\n\n🆓 Start your free trial: ${BOT_URL}`,
        `📌 *The most common mistake new Aviator players make:*\n\nWaiting too long. The game is designed to test your nerves. Our bot removes the guesswork — it tells you the optimal cash-out window.\n\n🚀 Try the free trial: ${BOT_URL}`,
    ];
    return { choices: [{ message: { content: pickRandom(tips) } }] };
}

function generateTestimonialPost() {
    const testimonials = [
        { text: "I was skeptical but tried the free trial. The accuracy shocked me. Bought the premium code immediately.", name: "Kevin R.", city: "Nairobi" },
        { text: "Used the free trial to test accuracy yesterday. It nailed 4 rounds in a row. Bought a code for my site today.", name: "Aisha M.", city: "Dubai" },
        { text: "Finally an Aviator tool that actually works. Been using it for 2 weeks. The predictions are consistently on point.", name: "Chidi O.", city: "Lagos" },
        { text: "Best $75 I've spent. Used it for a full 24 hours on SportyBet. More than covered the cost in the first hour.", name: "Tom K.", city: "Madrid" },
        { text: "I've tried other Aviator bots and they were useless. AviSignals actually works. The predictions are very accurate.", name: "James M.", city: "Sydney" },
        { text: "I was skeptical but tried the free trial. The accuracy shocked me. Bought the premium code immediately.", name: "Grace W.", city: "Mombasa" },
        { text: "Used the free trial to test accuracy yesterday. It nailed 4 rounds in a row. Bought a code for my site today.", name: "Brian O.", city: "Cape Town" },
        { text: "Finally an Aviator tool that actually works. Been using it for 2 weeks. The predictions are consistently on point.", name: "Amara K.", city: "Kampala" },
        { text: "My friend told me about AviSignals. I tried the free trial to see how the bot works. Got the paid code the same day.", name: "David N.", city: "London" },
        { text: "Best $75 I've spent. Used it for a full 24 hours on SportyBet. More than covered the cost in the first hour.", name: "Fatima H.", city: "Dar es Salaam" },
    ];
    const t = pickRandom(testimonials);
    const text = `💬 _"${t.text}"_\n— *${t.name}*, ${t.city}\n\n✅ The free trial is available right now — no payment needed to start.\n👉 ${BOT_URL}`;
    return { choices: [{ message: { content: text } }] };
}

// ─── Route to correct generator ──────────────────────────────
const GENERATORS = {
    sales_pitch: generateSalesPitch,
    success_story: generateSuccessStory,
    signal_tease: generateSignalTease,
    urgency: generateUrgencyPost,
    educational: generateEducationalPost,
    testimonial: generateTestimonialPost,
};


// ============================================================
// TELEGRAM API WRAPPER
// ============================================================

function telegramRequest(method, payload, retries = 3) {
    return new Promise((resolve, reject) => {
        if (!BOT_TOKEN) {
            console.warn('⚠️  TELEGRAM_BOT_TOKEN not set');
            return resolve(null);
        }

        const body = JSON.stringify(payload);
        const bodyBuf = Buffer.from(body, 'utf8');

        const options = {
            hostname: 'api.telegram.org',
            path: `/bot${BOT_TOKEN}/${method}`,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Content-Length': bodyBuf.length
            }
        };

        const req = https.request(options, (res) => {
            let raw = '';
            res.on('data', chunk => raw += chunk);
            res.on('end', () => {
                try {
                    const parsed = JSON.parse(raw);
                    if (!parsed.ok && retries > 0) {
                        // Telegram rate limit
                        if (parsed.error_code === 429) {
                            const wait = (parsed.parameters?.retry_after || 5) * 1000;
                            console.warn(`⏳ Telegram rate limit — retrying in ${wait}ms`);
                            setTimeout(() => telegramRequest(method, payload, retries - 1).then(resolve).catch(reject), wait);
                        } else {
                            console.error(`❌ Telegram API error [${method}]:`, parsed.description);
                            resolve(parsed);
                        }
                    } else {
                        resolve(parsed);
                    }
                } catch (_) { resolve(null); }
            });
        });

        req.on('error', (e) => {
            console.error(`❌ Telegram request error [${method}]:`, e.message);
            if (retries > 0) {
                setTimeout(() => telegramRequest(method, payload, retries - 1).then(resolve).catch(reject), 2000);
            } else {
                resolve(null);
            }
        });

        req.write(bodyBuf);
        req.end();
    });
}

function sendToChannel(text, targetChannelId = CHANNEL_ID) {
    return telegramRequest('sendMessage', {
        chat_id: targetChannelId,
        text,
        parse_mode: 'Markdown',
        link_preview_options: { is_disabled: true }
    });
}

function sendToAdmin(text) {
    if (!ADMIN_CHAT) {
        console.warn('⚠️  TELEGRAM_CHAT_ID not set — cannot message admin');
        return Promise.resolve(null);
    }
    return telegramRequest('sendMessage', {
        chat_id: ADMIN_CHAT,
        text,
        parse_mode: 'Markdown',
        link_preview_options: { is_disabled: true }
    });
}



// ============================================================
// CHANNEL BROADCASTER — runs at :15 and :45
// ============================================================
async function runChannelPost() {
    const type = nextContentType();
    const generator = GENERATORS[type];

    console.log(`📢 Broadcasting [${type}] to Telegram channel...`);

    try {
        const completion = await generator();
        let text = completion.choices[0]?.message?.content?.trim() || '';

        // Strip any markdown fences the AI sneaks in
        text = text.replace(/```html?/gi, '').replace(/```/g, '').trim();

        if (!text) {
            console.warn('⚠️  Empty post generated — skipping.');
            return;
        }

        const result = await sendToChannel(text);
        if (result?.ok) {
            addToHistory(type, text.replace(/<[^>]*>/g, '')); // strip HTML for history preview
            console.log(`✅ Channel post sent [${type}]`);
        } else {
            console.error(`❌ Channel post failed [${type}]:`, result?.description);
        }

        // Also post to agent channel if configured
        const AGENT_CHANNEL_ID = process.env.AGENT_TELEGRAM_CHANNEL_ID;
        if (AGENT_CHANNEL_ID) {
            const translatedText = translateToAgent(text);
            console.log(`📢 Broadcasting translated [${type}] to Agent Telegram channel...`);
            const agentResult = await sendToChannel(translatedText, AGENT_CHANNEL_ID);
            if (agentResult?.ok) {
                console.log(`✅ Agent Channel post sent [${type}]`);
            } else {
                console.error(`❌ Agent Channel post failed [${type}]:`, agentResult?.description);
            }
        }

    } catch (err) {
        console.error(`❌ Channel post error [${type}]:`, err.message);
    }
}

// ============================================================
// ADMIN BOT — answers your questions about the business
// ============================================================

// Track last update_id so we don't process the same message twice
let lastUpdateId = 0;

// Live business data for admin context
async function fetchLiveContext() {
    try {
        const [users, subs, payments, online] = await Promise.allSettled([
            supabase.from('profiles').select('id', { count: 'exact', head: true }),
            supabase.from('activations').select('code_type', { count: 'exact', head: false }),
            supabase.from('payments').select('amount').eq('status', 'success')
                .gte('created_at', new Date(new Date().setHours(0, 0, 0, 0)).toISOString()),
            Promise.resolve(global.activeSessions?.size || 0)
        ]);

        const subsData = subs.status === 'fulfilled' ? subs.value.data : [];
        const paymentsData = payments.status === 'fulfilled' ? payments.value.data : [];
        const totalRevToday = paymentsData.reduce((s, p) => s + Number(p.amount || 0), 0);
        const planBreakdown = (subsData || []).reduce((acc, s) => {
            acc[s.code_type] = (acc[s.code_type] || 0) + 1; return acc;
        }, {});

        const planStr = Object.entries(planBreakdown).map(([k, v]) => `${(k || 'UNKNOWN').replace(/_/g, ' ')}: ${v}`).join(', ') || 'None';

        return {
            totalUsers: users.status === 'fulfilled' ? (users.value.count || 0) : '?',
            activeSubscribers: (subsData || []).length,
            planBreakdown: planStr,
            revenueToday: `$${totalRevToday.toFixed(2)}`,
            paymentsToday: paymentsData.length,
            onlineNow: online,
            postsToday: postHistory.length,
            lastPostType: postHistory[postHistory.length - 1]?.type || 'none',
        };
    } catch (_) {
        return { error: 'Could not fetch live data' };
    }
}

const ADMIN_SYSTEM_PROMPT = `You are ARIA, the AviSignals AI Business Assistant — the founder's private, always-on COO via Telegram.

BUSINESS OVERVIEW:
- AviSignals: AI-powered Aviator game prediction platform
- Free tier: Free Trial code (60-min session, ClassyBet/JetBet only)
- Paid tier: $75 = 24-hour continuous access code (weekly $250, monthly $800)
- Payments: (card/Mobile money), USDT
- Target market: Global — Africa, Europe, Asia, Americas
- Key channels: Telegram channel, WhatsApp, website (avisignals.com)
- Telegram channel posts 2x/hour (content broadcast) + 3 daily marketing events

MARKETING EVENTS (scheduled daily):
- 1:00 PM EAT — Code Giveaway in channel
- 6:30–7:00 PM EAT — Live Session Countdown in channel
- 3 admin briefings: 7AM, 12PM, 9PM EAT

YOUR ROLE:
- Answer any business question immediately and precisely
- Give live stats when asked (injected into your context below)
- Suggest growth tactics, conversion improvements, retention strategies
- Draft posts, emails, or messages on request
- Flag urgent issues (payment failures, low conversions, unusual patterns)
- Help admin run channel events (giveaways, countdowns) on demand

AVAILABLE ADMIN COMMANDS (remind user if relevant):
/status — live metrics snapshot
/briefing — full styled business briefing
/revenue — revenue-only snapshot
/users — user count + today's signups
/giveaway — trigger a code giveaway to channel NOW
/countdown — trigger live session countdown to channel NOW
/post — trigger a random channel broadcast NOW
/broadcast [msg] — post a custom message to channel
/help — full command list

TONE: Sharp, direct, loyal COO. Data-driven, no filler. Short sentences.
FORMAT: Telegram Markdown only — *bold*, _italic_, \`code\`, bullet points with -`;

// ============================================================
// ADMIN BRIEFING — full styled business summary
// ============================================================
async function sendAdminBriefing(label = 'Scheduled') {
    const ctx = await fetchLiveContext();
    const now = new Date().toLocaleTimeString('en-KE', { timeZone: 'Africa/Nairobi', hour: '2-digit', minute: '2-digit' });
    const date = new Date().toLocaleDateString('en-KE', { timeZone: 'Africa/Nairobi', weekday: 'short', day: 'numeric', month: 'short' });

    const briefing = `📋 *${label.toUpperCase()} BRIEFING — ${date} ${now}*\n\n` +
        `👥 *Users:* ${ctx.totalUsers} total\n` +
        `✅ *Active Subs:* ${ctx.activeSubscribers}\n` +
        `📦 *Plans:* ${ctx.planBreakdown}\n` +
        `💰 *Revenue Today:* ${ctx.revenueToday} (${ctx.paymentsToday} payments)\n` +
        `🟢 *Online Now:* ${ctx.onlineNow}\n` +
        `📢 *Channel Posts:* ${ctx.postsToday} (last: _${ctx.lastPostType}_)\n\n` +
        `💡 _Use /help for admin commands_`;

    await sendToAdmin(briefing);
    console.log(`✅ ${label} briefing sent to admin`);
}

async function handleAdminMessage(message) {
    const text = message.text?.trim() || '';
    const chatId = message.chat.id;
    const fromId = message.from?.id;

    // Security — only respond to the configured admin chat
    if (String(chatId) !== String(ADMIN_CHAT) && String(fromId) !== String(ADMIN_CHAT)) {
        console.log(`⚠️  Ignored message from unauthorized chat: ${chatId}`);
        return;
    }

    console.log(`📩 Admin message received: "${text.slice(0, 60)}"`);

    // ── /status ────────────────────────────────────────────────
    if (text.startsWith('/status') || text.toLowerCase() === 'status') {
        const ctx = await fetchLiveContext();
        const msg = `📊 *Live Status*\n\n` +
            `👥 Users: *${ctx.totalUsers}* | Active subs: *${ctx.activeSubscribers}*\n` +
            `💰 Revenue today: *${ctx.revenueToday}* (${ctx.paymentsToday} txns)\n` +
            `📦 Plans: ${ctx.planBreakdown}\n` +
            `🟢 Online now: *${ctx.onlineNow}*\n` +
            `📢 Posts today: *${ctx.postsToday}* (last: _${ctx.lastPostType}_)\n` +
            `🕐 ${new Date().toLocaleTimeString('en-KE', { timeZone: 'Africa/Nairobi' })}`;
        await telegramRequest('sendMessage', { chat_id: chatId, text: msg, parse_mode: 'Markdown' });
        return;
    }

    // ── /briefing ──────────────────────────────────────────────
    if (text.startsWith('/briefing')) {
        await telegramRequest('sendMessage', { chat_id: chatId, text: '📋 Generating briefing...', parse_mode: 'Markdown' });
        await sendAdminBriefing('On-Demand');
        return;
    }

    // ── /revenue ───────────────────────────────────────────────
    if (text.startsWith('/revenue')) {
        const ctx = await fetchLiveContext();
        const msg = `💰 *Revenue Snapshot*\n\n` +
            `Today: *${ctx.revenueToday}* across ${ctx.paymentsToday} payments\n` +
            `Active subs: *${ctx.activeSubscribers}*\n` +
            `Plans: ${ctx.planBreakdown}`;
        await telegramRequest('sendMessage', { chat_id: chatId, text: msg, parse_mode: 'Markdown' });
        return;
    }

    // ── /users ─────────────────────────────────────────────────
    if (text.startsWith('/users')) {
        const ctx = await fetchLiveContext();
        // Count today's signups
        const todayStart = new Date(); todayStart.setHours(0, 0, 0, 0);
        const { count: newToday } = await supabase
            .from('profiles').select('id', { count: 'exact', head: true })
            .gte('created_at', todayStart.toISOString()).catch(() => ({ count: '?' }));
        const msg = `👥 *User Stats*\n\n` +
            `Total registered: *${ctx.totalUsers}*\n` +
            `New today: *${newToday ?? '?'}*\n` +
            `Active subscribers: *${ctx.activeSubscribers}*`;
        await telegramRequest('sendMessage', { chat_id: chatId, text: msg, parse_mode: 'Markdown' });
        return;
    }

    // ── /giveaway ──────────────────────────────────────────────
    if (text.startsWith('/giveaway')) {
        await telegramRequest('sendMessage', { chat_id: chatId, text: '🎁 Triggering giveaway to channel...', parse_mode: 'Markdown' });
        const marketingBot = global.marketingBotInstance;
        if (marketingBot) {
            await marketingBot.runCodeGiveaway();
            await telegramRequest('sendMessage', { chat_id: chatId, text: '✅ Giveaway posted to channel.', parse_mode: 'Markdown' });
        } else {
            await telegramRequest('sendMessage', { chat_id: chatId, text: '⚠️ Marketing bot not running.', parse_mode: 'Markdown' });
        }
        return;
    }

    // ── /countdown ─────────────────────────────────────────────
    if (text.startsWith('/countdown')) {
        await telegramRequest('sendMessage', { chat_id: chatId, text: '⏳ Triggering live session countdown...', parse_mode: 'Markdown' });
        const marketingBot = global.marketingBotInstance;
        if (marketingBot) {
            await marketingBot.runCountdownSequence();
            await telegramRequest('sendMessage', { chat_id: chatId, text: '✅ Countdown posted to channel.', parse_mode: 'Markdown' });
        } else {
            await telegramRequest('sendMessage', { chat_id: chatId, text: '⚠️ Marketing bot not running.', parse_mode: 'Markdown' });
        }
        return;
    }

    // ── /broadcast ─────────────────────────────────────────────
    if (text.startsWith('/broadcast ')) {
        const customMsg = text.replace('/broadcast ', '').trim();
        if (!customMsg) {
            await telegramRequest('sendMessage', { chat_id: chatId, text: '⚠️ Usage: /broadcast Your message here', parse_mode: 'Markdown' });
            return;
        }
        const result = await sendToChannel(customMsg);
        const reply = result?.ok ? '✅ Message posted to channel.' : '❌ Failed to post message.';
        await telegramRequest('sendMessage', { chat_id: chatId, text: reply, parse_mode: 'Markdown' });
        return;
    }

    // ── /post ──────────────────────────────────────────────────
    if (text.startsWith('/post') || text.toLowerCase() === 'post now') {
        const parts = text.split(' ');
        const postType = parts[1]; // optional: /post sales_pitch
        await telegramRequest('sendMessage', { chat_id: chatId, text: '📢 Posting to channel now...', parse_mode: 'Markdown' });
        await runChannelPost(postType);
        await telegramRequest('sendMessage', { chat_id: chatId, text: '✅ Post sent to channel.', parse_mode: 'Markdown' });
        return;
    }

    // ── /help ──────────────────────────────────────────────────
    if (text.startsWith('/help') || text.startsWith('/start')) {
        const helpMsg =
            `🤖 *ARIA — AviSignals Admin Bot*\n\n` +
            `*QUICK COMMANDS*\n` +
            `• /status — live metrics\n` +
            `• /briefing — full business briefing\n` +
            `• /revenue — revenue snapshot\n` +
            `• /users — user count + today's signups\n` +
            `• /giveaway — run a code giveaway NOW\n` +
            `• /countdown — start live session countdown NOW\n` +
            `• /post — random channel broadcast NOW\n` +
            `• /broadcast [msg] — post custom message to channel\n\n` +
            `*OR* just ask me anything in plain English!\n` +
            `_e.g. "what should I focus on today?" or "write a win post"_`;
        await telegramRequest('sendMessage', { chat_id: chatId, text: helpMsg, parse_mode: 'Markdown' });
        return;
    }

    // For everything else — pass to AI with live context injected
    try {
        const ctx = await fetchLiveContext();

        const contextBlock = `\nLIVE BUSINESS DATA (as of ${new Date().toLocaleTimeString('en-KE', { timeZone: 'Africa/Nairobi' })}):\n` +
            Object.entries(ctx).map(([k, v]) => `- ${k}: ${v}`).join('\n');

        const completion = await groq.chat.completions.create({
            messages: [
                { role: 'system', content: ADMIN_SYSTEM_PROMPT + contextBlock },
                { role: 'user', content: text }
            ],
            model: 'llama-3.3-70b-versatile',
            temperature: 0.6,
            max_tokens: 600
        });

        const reply = completion.choices[0]?.message?.content?.trim()
            || 'Sorry, I had trouble generating a response. Try again.';

        await telegramRequest('sendMessage', {
            chat_id: chatId,
            text: reply,
            parse_mode: 'Markdown'
        });

    } catch (err) {
        console.error('❌ Admin bot AI error:', err.message);
        await telegramRequest('sendMessage', {
            chat_id: chatId,
            text: '⚠️ I had an error processing that. Try again in a moment.',
            parse_mode: 'Markdown'
        });
    }
}

// ============================================================
// WEBHOOK MODE — replaces long-polling
// Telegram pushes updates to POST /api/telegram/agent-webhook
// This eliminates the "Conflict" error that occurs when Render
// briefly runs two instances during zero-downtime deployments.
// ============================================================

/**
 * Called by the Express route in app.js (or routes/telegram.js)
 * whenever Telegram sends a POST to the agent webhook endpoint.
 */
async function processWebhookUpdate(update) {
    try {
        if (update.message) {
            await handleAdminMessage(update.message);
        }
        // callback_query handling is done by routes/telegram.js webhook
    } catch (err) {
        console.error('❌ Webhook update error:', err.message);
    }
}

/**
 * Registers the webhook with Telegram once on startup.
 * Safe to call multiple times — Telegram is idempotent if URL is the same.
 */
async function registerWebhook() {
    if (!BOT_TOKEN) {
        console.warn('⚠️  TELEGRAM_BOT_TOKEN not set — skipping webhook registration.');
        return;
    }
    const baseUrl = (process.env.BASE_URL || '').trim().replace(/\/+$/, '');
    if (!baseUrl) {
        console.warn('⚠️  BASE_URL not set — cannot register Telegram webhook. Set BASE_URL=https://back.avisignals.com in Render.');
        return;
    }
    const webhookUrl = `${baseUrl}/api/telegram/agent-webhook`;
    console.log(`🔗 Registering Telegram webhook → ${webhookUrl}`);
    const res = await telegramRequest('setWebhook', {
        url: webhookUrl,
        allowed_updates: ['message', 'callback_query']
    });
    if (res?.ok) {
        console.log('✅ Telegram webhook registered successfully.');
    } else {
        console.error('❌ Failed to register Telegram webhook:', res?.description);
    }
}

// Legacy stub — no-op now that we use webhooks
function stopPolling() {
    console.log('ℹ️  Polling is disabled — using webhooks.');
}

// ============================================================
// STARTUP
// ============================================================
function startTelegramAgent() {
    console.log('🚀 AviSignals Telegram Agent v3 — Initializing...');

    // ── Channel content broadcast: 2x per hour (:15, :45), 6am–11pm ──
    cron.schedule('15,45 6-23 * * *', runChannelPost);

    // ── Daily Admin Briefings (EAT timezone = UTC+3) ──────────────────
    // 🌅 Morning briefing: 7:00 AM EAT = 04:00 UTC
    cron.schedule('0 4 * * *', () => sendAdminBriefing('🌅 Morning'));
    // ☀️ Midday briefing:  12:00 PM EAT = 09:00 UTC
    cron.schedule('0 9 * * *', () => sendAdminBriefing('☀️ Midday'));
    // 🌙 Night briefing:    9:00 PM EAT = 18:00 UTC
    cron.schedule('0 18 * * *', () => sendAdminBriefing('🌙 Night'));

    // ── Register webhook with Telegram (replaces polling) ─────────────
    // Delay slightly so the HTTP server is definitely up before we call Telegram
    setTimeout(registerWebhook, 5000);

    // ── Initialize Marketing Bot (countdowns + giveaways) ─────────────
    const TelegramMarketingBot = require('../marketing/telegramMarketing');
    const marketingBot = new TelegramMarketingBot();
    global.marketingBotInstance = marketingBot; // expose for admin commands
    marketingBot.start();

    // ── Initialize Referral Agent Marketing Bot ──────────────────
    const TelegramAgentMarketingBot = require('../marketing/telegramAgentMarketing');
    const agentMarketingBot = new TelegramAgentMarketingBot();
    global.agentMarketingBotInstance = agentMarketingBot;
    agentMarketingBot.start();

    // ── Initialize Premium Signals Bot ────────────────────────────
    const TelegramSignalsMarketingBot = require('../marketing/telegramSignalsMarketing');
    const signalsMarketingBot = new TelegramSignalsMarketingBot();
    global.signalsMarketingBotInstance = signalsMarketingBot;
    signalsMarketingBot.start();

    console.log('✅ Telegram Agent v3 ready:');
    console.log('   📢 Channel broadcast  — 2x/hour (:15, :45) 6am–11pm EAT');
    console.log('   📋 Admin briefings    — 7AM, 12PM, 9PM EAT (no hourly spam)');
    console.log('   🎁 Code giveaway      — 1:00 PM EAT daily');
    console.log('   🔴 Live countdown     — 6:30→7:00 PM EAT daily');
    console.log('   👂 Admin bot polling  — always on');
    console.log(`   💬 Admin chat ID      — ${ADMIN_CHAT || 'NOT SET'}`);
    console.log(`   📣 Channel            — ${CHANNEL_ID}`);
}

module.exports = {
    startTelegramAgent,
    runChannelPost,
    sendToAdmin,
    sendToChannel,
    stopPolling,
    processWebhookUpdate,   // consumed by the Express webhook route
    registerWebhook
};
