// ============================================================
// telegramAgent.js — AviSignals Telegram Agent v2
//
// Three jobs in one file:
//  1. CHANNEL BROADCASTER  — posts 3x per hour to the public
//     channel with rotating content (sales pitch, success story,
//     signal tease, urgency post, educational, testimonial)
//  2. ADMIN BOT            — answers your questions about the
//     business in real-time via Telegram private chat
//  3. SOCIAL MEDIA SYNC    — shares the daily content calendar
//     generated by socialMediaAgent directly to admin
//
// Improvements over v1:
//  - 3x per hour (was once every 3 hours)
//  - 6 rotating content types — never repeats same format twice in a row
//  - Post history fed back to AI so it never repeats content
//  - Admin bot with polling — you can message it any question
//  - Admin bot has full business context + live Supabase data
//  - Proper byte-length Content-Length (fixes Unicode bugs)
//  - Retry logic on Telegram API failures
//  - Clean HTML formatting for channel posts
// ============================================================

'use strict';

const cron = require('node-cron');
const https = require('https');
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY
);

// ─── Config ───────────────────────────────────────────────────
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const CHANNEL_ID = process.env.TELEGRAM_CHANNEL_ID || '@AviSignalsAviatorPredictorBot';
const ADMIN_CHAT = process.env.TELEGRAM_CHAT_ID;    // your personal Telegram chat ID
const SITE_URL = 'https://avisignals.com';
const BOT_URL = `${SITE_URL}/bot`;

// ─── Post history (in-memory, last 10 posts) ─────────────────
// Prevents repeating the same content
const postHistory = [];
const MAX_HISTORY = 10;

function addToHistory(type, preview) {
    postHistory.push({ type, preview: preview.slice(0, 80), at: new Date().toLocaleTimeString() });
    if (postHistory.length > MAX_HISTORY) postHistory.shift();
}

// ─── Content type rotation ────────────────────────────────────
const CONTENT_TYPES = [
    'sales_pitch',
    'success_story',
    'signal_tease',
    'urgency',
    'educational',
    'testimonial'
];
let contentTypeIndex = 0;

function nextContentType() {
    const type = CONTENT_TYPES[contentTypeIndex % CONTENT_TYPES.length];
    contentTypeIndex++;
    return type;
}

// ============================================================
// TEMPLATE CONTENT GENERATORS — AI-FREE, zero Groq tokens
// Same 6 content types, powered by rotating pre-written pools.
// ============================================================

function pickRandom(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

const SALES_PITCH_POOL = [
    `🚀 <b>Don't guess. Predict.</b>\n\nAviSignals uses real-time AI analysis to tell you when to cash out — before the round ends.\n\n🆓 Grab your FREE daily code at <a href="${BOT_URL}">avisignals.com/bot.html</a>\n💎 Want full 24H access? Just $75. No subscriptions.`,
    `🎯 <b>Your edge in Aviator starts here.</b>\n\n3,200+ members are using AviSignals daily to time their cash-outs with precision.\n\n🆓 Try it FREE — no payment needed to start.\n👉 <a href="${BOT_URL}">avisignals.com/bot.html</a>`,
    `⚡ <b>The smart way to play Aviator.</b>\n\nOur AI reads the game — you just follow the signal and cash out at the right moment.\n\n✅ Free daily code available right now.\n🔗 <a href="${BOT_URL}">avisignals.com/bot.html</a>`,
    `🔥 <b>Stop losing. Start predicting.</b>\n\nAviSignals gives you data-driven signals for every Aviator round on any site worldwide.\n\n🆓 One free code per day — no card required.\n📲 <a href="${BOT_URL}">Get started now</a>`,
    `💡 <b>What if you knew when to cash out?</b>\n\nThat's exactly what AviSignals does. AI-powered round analysis. Real-time signals.\n\n🎁 Your free code is waiting: <a href="${BOT_URL}">avisignals.com/bot.html</a>`,
];

const SUCCESS_STORIES = [
    { name: 'James M.', city: 'Sydney', start: 'AUD 8,000', end: 'AUD 150,000', site: '1xBet', days: 2 },
    { name: 'Grace W.', city: 'Mombasa', start: 'KES 5,000', end: 'KES 162,000', site: 'Betika', days: 1 },
    { name: 'Brian O.', city: 'Cape Town', start: 'R 3,000', end: 'R 41,000', site: 'Betway', days: 1 },
    { name: 'Amara K.', city: 'Kampala', start: 'UGX 50,000', end: 'UGX 1,900,000', site: 'Bangbet', days: 3 },
    { name: 'David N.', city: 'London', start: 'GBP 1,000', end: 'GBP 75,000', site: '1win', days: 2 },
    { name: 'Fatima H.', city: 'Dar es Salaam', start: 'TZS 20,000', end: 'TZS 880,000', site: 'Parimatch', days: 1 },
];
let storyIndex = 0;

function generateSalesPitch() {
    return { choices: [{ message: { content: pickRandom(SALES_PITCH_POOL) } }] };
}

function generateSuccessStory() {
    const s = SUCCESS_STORIES[storyIndex % SUCCESS_STORIES.length];
    storyIndex++;
    const text = `🏆 <b>Real member. Real results.</b>\n\n<i>"I started with ${s.start} on ${s.site}. After ${s.days} day(s) using AviSignals, I walked away with ${s.end}."</i>\n— <b>${s.name}</b>, ${s.city}\n\n🚀 Start your own story — grab your FREE code at <a href="${BOT_URL}">avisignals.com/bot.html</a>`;
    return { choices: [{ message: { content: text } }] };
}

function generateSignalTease() {
    const multipliers = ['7.4×', '12.1×', '3.8×', '18.6×', '5.2×', '9.9×', '22.4×'];
    const multi = pickRandom(multipliers);
    const text = `📡 <b>Signal confirmed: ${multi}</b>\n\nOur bot called it. Members who followed the signal cashed out at exactly the right moment — again. 🎯\n\n🆓 Get your free daily code and see it for yourself:\n👉 <a href="${BOT_URL}">avisignals.com/bot.html</a>`;
    return { choices: [{ message: { content: text } }] };
}

function generateUrgencyPost() {
    const hour = new Date().getHours();
    const session = hour < 12 ? 'morning session' : hour < 18 ? 'afternoon session' : "tonight's session";
    const text = `⏰ <b>The ${session} is LIVE right now.</b>\n\nMembers are already using their codes. Don't miss today's rounds.\n\n🆓 Your free code resets every day — use it or lose it.\n💎 Want 24H access? Get a premium code for $75.\n\n👉 <a href="${BOT_URL}">avisignals.com/bot.html</a>`;
    return { choices: [{ message: { content: text } }] };
}

function generateEducationalPost() {
    const tips = [
        `📌 <b>Pro Tip: Cash out early on high-volatility rounds.</b>\n\nWhen the AviSignals bot shows a low confidence score, take your profit at 1.5× or 2× instead of pushing for 10×. Consistency beats luck.\n\n💡 Get the bot: <a href="${BOT_URL}">avisignals.com/bot.html</a>`,
        `📌 <b>Free vs Premium Code — what's the difference?</b>\n\n🆓 Free code: 30-minute trial session, assigned site.\n💎 Premium code: Full 24H access, any site worldwide.\n\nBoth give you real-time AI signals. Try free first.\n👉 <a href="${BOT_URL}">avisignals.com/bot.html</a>`,
        `📌 <b>Timing your bet matters more than bet size.</b>\n\nA KES 100 bet at the right moment beats a KES 1,000 bet at the wrong one. AviSignals tells you exactly when to enter — and when to hold off.\n\n🔗 <a href="${BOT_URL}">avisignals.com/bot.html</a>`,
        `💡 <b>How to use AviSignals and play at the same time:</b>\n\n1. Open the bot on your phone\n2. Open your betting site on the same device (split screen) or another device\n3. Follow the signal — cash out when the bot says GO\n\n🆓 Get your free code: <a href="${BOT_URL}">avisignals.com/bot.html</a>`,
        `📌 <b>The most common mistake new Aviator players make:</b>\n\nWaiting too long. The game is designed to test your nerves. Our bot removes the guesswork — it tells you the optimal cash-out window based on round data.\n\n🚀 Try it free: <a href="${BOT_URL}">avisignals.com/bot.html</a>`,
    ];
    return { choices: [{ message: { content: pickRandom(tips) } }] };
}

function generateTestimonialPost() {
    const testimonials = [
        { text: "I was skeptical but tried the free code on Betika. The accuracy shocked me. Bought the 24H code immediately.", name: "Kevin R.", city: "Nairobi" },
        { text: "Used it on 1xBet for the first time yesterday. My free code nailed 4 rounds in a row. I'm sold.", name: "Aisha M.", city: "Dubai" },
        { text: "Finally an Aviator tool that actually works. Been using it for 2 weeks. The predictions are consistently on point.", name: "Chidi O.", city: "Lagos" },
        { text: "My friend told me about AviSignals. I tried the free daily code and I was impressed. Got the paid code the same day.", name: "Susan W.", city: "Johannesburg" },
        { text: "Best $75 I've spent. Used it for a full 24 hours on SportyBet. More than covered the cost in the first hour.", name: "Tom K.", city: "Madrid" },
    ];
    const t = pickRandom(testimonials);
    const text = `💬 <i>"${t.text}"</i>\n— <b>${t.name}</b>, ${t.city}\n\n✅ The free daily code is available right now — no payment needed to start.\n👉 <a href="${BOT_URL}">avisignals.com/bot.html</a>`;
    return { choices: [{ message: { content: text } }] };
}

// ─── Route to correct generator ──────────────────────────────
const GENERATORS = {
    sales_pitch: generateSalesPitch,
    success_story: generateSuccessStory,
    signal_tease: generateSignalTease,
    urgency: generateUrgencyPost,
    educational: generateEducationalPost,
    testimonial: generateTestimonialPost,
};


// ============================================================
// TELEGRAM API WRAPPER
// ============================================================

function telegramRequest(method, payload, retries = 3) {
    return new Promise((resolve, reject) => {
        if (!BOT_TOKEN) {
            console.warn('⚠️  TELEGRAM_BOT_TOKEN not set');
            return resolve(null);
        }

        const body = JSON.stringify(payload);
        const bodyBuf = Buffer.from(body, 'utf8');

        const options = {
            hostname: 'api.telegram.org',
            path: `/bot${BOT_TOKEN}/${method}`,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Content-Length': bodyBuf.length
            }
        };

        const req = https.request(options, (res) => {
            let raw = '';
            res.on('data', chunk => raw += chunk);
            res.on('end', () => {
                try {
                    const parsed = JSON.parse(raw);
                    if (!parsed.ok && retries > 0) {
                        // Telegram rate limit
                        if (parsed.error_code === 429) {
                            const wait = (parsed.parameters?.retry_after || 5) * 1000;
                            console.warn(`⏳ Telegram rate limit — retrying in ${wait}ms`);
                            setTimeout(() => telegramRequest(method, payload, retries - 1).then(resolve).catch(reject), wait);
                        } else {
                            console.error(`❌ Telegram API error [${method}]:`, parsed.description);
                            resolve(parsed);
                        }
                    } else {
                        resolve(parsed);
                    }
                } catch (_) { resolve(null); }
            });
        });

        req.on('error', (e) => {
            console.error(`❌ Telegram request error [${method}]:`, e.message);
            if (retries > 0) {
                setTimeout(() => telegramRequest(method, payload, retries - 1).then(resolve).catch(reject), 2000);
            } else {
                resolve(null);
            }
        });

        req.write(bodyBuf);
        req.end();
    });
}

function sendToChannel(text) {
    return telegramRequest('sendMessage', {
        chat_id: CHANNEL_ID,
        text,
        parse_mode: 'HTML',
        link_preview_options: { is_disabled: true }
    });
}

function sendToAdmin(text) {
    if (!ADMIN_CHAT) {
        console.warn('⚠️  TELEGRAM_CHAT_ID not set — cannot message admin');
        return Promise.resolve(null);
    }
    return telegramRequest('sendMessage', {
        chat_id: ADMIN_CHAT,
        text,
        parse_mode: 'Markdown',
        link_preview_options: { is_disabled: true }
    });
}



// ============================================================
// CHANNEL BROADCASTER — runs at :15 and :45
// ============================================================
async function runChannelPost() {
    const type = nextContentType();
    const generator = GENERATORS[type];

    console.log(`📢 Broadcasting [${type}] to Telegram channel...`);

    try {
        const completion = await generator();
        let text = completion.choices[0]?.message?.content?.trim() || '';

        // Strip any markdown fences the AI sneaks in
        text = text.replace(/```html?/gi, '').replace(/```/g, '').trim();

        if (!text) {
            console.warn('⚠️  Empty post generated — skipping.');
            return;
        }

        const result = await sendToChannel(text);
        if (result?.ok) {
            addToHistory(type, text.replace(/<[^>]*>/g, '')); // strip HTML for history preview
            console.log(`✅ Channel post sent [${type}]`);
        } else {
            console.error(`❌ Channel post failed [${type}]:`, result?.description);
        }

    } catch (err) {
        console.error(`❌ Channel post error [${type}]:`, err.message);
    }
}

// ============================================================
// ADMIN BOT — answers your questions about the business
// ============================================================

// Track last update_id so we don't process the same message twice
let lastUpdateId = 0;

// Live business data for admin context
async function fetchLiveContext() {
    try {
        const [users, subs, payments, online] = await Promise.allSettled([
            supabase.from('profiles').select('id', { count: 'exact', head: true }),
            supabase.from('activations').select('code_type', { count: 'exact', head: false }),
            supabase.from('payments').select('amount').eq('status', 'success')
                .gte('created_at', new Date(new Date().setHours(0, 0, 0, 0)).toISOString()),
            Promise.resolve(global.activeSessions?.size || 0)
        ]);

        const subsData = subs.status === 'fulfilled' ? subs.value.data : [];
        const paymentsData = payments.status === 'fulfilled' ? payments.value.data : [];
        const totalRevToday = paymentsData.reduce((s, p) => s + Number(p.amount || 0), 0);
        const planBreakdown = (subsData || []).reduce((acc, s) => {
            acc[s.code_type] = (acc[s.code_type] || 0) + 1; return acc;
        }, {});
        
        const planStr = Object.entries(planBreakdown).map(([k, v]) => `${(k || 'UNKNOWN').replace(/_/g, ' ')}: ${v}`).join(', ') || 'None';

        return {
            totalUsers: users.status === 'fulfilled' ? (users.value.count || 0) : '?',
            activeSubscribers: (subsData || []).length,
            planBreakdown: planStr,
            revenueToday: `$${totalRevToday.toFixed(2)}`,
            paymentsToday: paymentsData.length,
            onlineNow: online,
            postsToday: postHistory.length,
            lastPostType: postHistory[postHistory.length - 1]?.type || 'none',
        };
    } catch (_) {
        return { error: 'Could not fetch live data' };
    }
}

const ADMIN_SYSTEM_PROMPT = `You are ARIA, the AviSignals AI Business Assistant — the founder's private, always-on COO via Telegram.

BUSINESS OVERVIEW:
- AviSignals: AI-powered Aviator game prediction platform
- Free tier: 1 free daily prediction code (30-min session)
- Paid tier: $75 = 24-hour continuous access code
- Payments: Paystack (card/M-Pesa), USDT, Selar
- Target market: Global — Africa, Europe, Asia, Americas
- Key channels: Telegram channel, WhatsApp, website (avisignals.com)
- Telegram channel posts 2x/hour (content broadcast) + 3 daily marketing events

MARKETING EVENTS (scheduled daily):
- 1:00 PM EAT — Code Giveaway in channel
- 6:30–7:00 PM EAT — Live Session Countdown in channel
- 3 admin briefings: 7AM, 12PM, 9PM EAT

YOUR ROLE:
- Answer any business question immediately and precisely
- Give live stats when asked (injected into your context below)
- Suggest growth tactics, conversion improvements, retention strategies
- Draft posts, emails, or messages on request
- Flag urgent issues (payment failures, low conversions, unusual patterns)
- Help admin run channel events (giveaways, countdowns) on demand

AVAILABLE ADMIN COMMANDS (remind user if relevant):
/status — live metrics snapshot
/briefing — full styled business briefing
/revenue — revenue-only snapshot
/users — user count + today's signups
/giveaway — trigger a code giveaway to channel NOW
/countdown — trigger live session countdown to channel NOW
/post — trigger a random channel broadcast NOW
/broadcast [msg] — post a custom message to channel
/help — full command list

TONE: Sharp, direct, loyal COO. Data-driven, no filler. Short sentences.
FORMAT: Telegram Markdown only — *bold*, _italic_, \`code\`, bullet points with -`;

// ============================================================
// ADMIN BRIEFING — full styled business summary
// ============================================================
async function sendAdminBriefing(label = 'Scheduled') {
    const ctx = await fetchLiveContext();
    const now = new Date().toLocaleTimeString('en-KE', { timeZone: 'Africa/Nairobi', hour: '2-digit', minute: '2-digit' });
    const date = new Date().toLocaleDateString('en-KE', { timeZone: 'Africa/Nairobi', weekday: 'short', day: 'numeric', month: 'short' });

    const briefing = `📋 *${label.toUpperCase()} BRIEFING — ${date} ${now}*\n\n` +
        `👥 *Users:* ${ctx.totalUsers} total\n` +
        `✅ *Active Subs:* ${ctx.activeSubscribers}\n` +
        `📦 *Plans:* ${ctx.planBreakdown}\n` +
        `💰 *Revenue Today:* ${ctx.revenueToday} (${ctx.paymentsToday} payments)\n` +
        `🟢 *Online Now:* ${ctx.onlineNow}\n` +
        `📢 *Channel Posts:* ${ctx.postsToday} (last: _${ctx.lastPostType}_)\n\n` +
        `💡 _Use /help for admin commands_`;

    await sendToAdmin(briefing);
    console.log(`✅ ${label} briefing sent to admin`);
}

async function handleAdminMessage(message) {
    const text = message.text?.trim() || '';
    const chatId = message.chat.id;
    const fromId = message.from?.id;

    // Security — only respond to the configured admin chat
    if (String(chatId) !== String(ADMIN_CHAT) && String(fromId) !== String(ADMIN_CHAT)) {
        console.log(`⚠️  Ignored message from unauthorized chat: ${chatId}`);
        return;
    }

    console.log(`📩 Admin message received: "${text.slice(0, 60)}"`);

    // ── /status ────────────────────────────────────────────────
    if (text.startsWith('/status') || text.toLowerCase() === 'status') {
        const ctx = await fetchLiveContext();
        const msg = `📊 *Live Status*\n\n` +
            `👥 Users: *${ctx.totalUsers}* | Active subs: *${ctx.activeSubscribers}*\n` +
            `💰 Revenue today: *${ctx.revenueToday}* (${ctx.paymentsToday} txns)\n` +
            `📦 Plans: ${ctx.planBreakdown}\n` +
            `🟢 Online now: *${ctx.onlineNow}*\n` +
            `📢 Posts today: *${ctx.postsToday}* (last: _${ctx.lastPostType}_)\n` +
            `🕐 ${new Date().toLocaleTimeString('en-KE', { timeZone: 'Africa/Nairobi' })}`;
        await telegramRequest('sendMessage', { chat_id: chatId, text: msg, parse_mode: 'Markdown' });
        return;
    }

    // ── /briefing ──────────────────────────────────────────────
    if (text.startsWith('/briefing')) {
        await telegramRequest('sendMessage', { chat_id: chatId, text: '📋 Generating briefing...', parse_mode: 'Markdown' });
        await sendAdminBriefing('On-Demand');
        return;
    }

    // ── /revenue ───────────────────────────────────────────────
    if (text.startsWith('/revenue')) {
        const ctx = await fetchLiveContext();
        const msg = `💰 *Revenue Snapshot*\n\n` +
            `Today: *${ctx.revenueToday}* across ${ctx.paymentsToday} payments\n` +
            `Active subs: *${ctx.activeSubscribers}*\n` +
            `Plans: ${ctx.planBreakdown}`;
        await telegramRequest('sendMessage', { chat_id: chatId, text: msg, parse_mode: 'Markdown' });
        return;
    }

    // ── /users ─────────────────────────────────────────────────
    if (text.startsWith('/users')) {
        const ctx = await fetchLiveContext();
        // Count today's signups
        const todayStart = new Date(); todayStart.setHours(0,0,0,0);
        const { count: newToday } = await supabase
            .from('profiles').select('id', { count: 'exact', head: true })
            .gte('created_at', todayStart.toISOString()).catch(() => ({ count: '?' }));
        const msg = `👥 *User Stats*\n\n` +
            `Total registered: *${ctx.totalUsers}*\n` +
            `New today: *${newToday ?? '?'}*\n` +
            `Active subscribers: *${ctx.activeSubscribers}*`;
        await telegramRequest('sendMessage', { chat_id: chatId, text: msg, parse_mode: 'Markdown' });
        return;
    }

    // ── /giveaway ──────────────────────────────────────────────
    if (text.startsWith('/giveaway')) {
        await telegramRequest('sendMessage', { chat_id: chatId, text: '🎁 Triggering giveaway to channel...', parse_mode: 'Markdown' });
        const marketingBot = global.marketingBotInstance;
        if (marketingBot) {
            await marketingBot.runCodeGiveaway();
            await telegramRequest('sendMessage', { chat_id: chatId, text: '✅ Giveaway posted to channel.', parse_mode: 'Markdown' });
        } else {
            await telegramRequest('sendMessage', { chat_id: chatId, text: '⚠️ Marketing bot not running.', parse_mode: 'Markdown' });
        }
        return;
    }

    // ── /countdown ─────────────────────────────────────────────
    if (text.startsWith('/countdown')) {
        await telegramRequest('sendMessage', { chat_id: chatId, text: '⏳ Triggering live session countdown...', parse_mode: 'Markdown' });
        const marketingBot = global.marketingBotInstance;
        if (marketingBot) {
            await marketingBot.runCountdownSequence();
            await telegramRequest('sendMessage', { chat_id: chatId, text: '✅ Countdown posted to channel.', parse_mode: 'Markdown' });
        } else {
            await telegramRequest('sendMessage', { chat_id: chatId, text: '⚠️ Marketing bot not running.', parse_mode: 'Markdown' });
        }
        return;
    }

    // ── /broadcast ─────────────────────────────────────────────
    if (text.startsWith('/broadcast ')) {
        const customMsg = text.replace('/broadcast ', '').trim();
        if (!customMsg) {
            await telegramRequest('sendMessage', { chat_id: chatId, text: '⚠️ Usage: /broadcast Your message here', parse_mode: 'Markdown' });
            return;
        }
        const result = await sendToChannel(customMsg);
        const reply = result?.ok ? '✅ Message posted to channel.' : '❌ Failed to post message.';
        await telegramRequest('sendMessage', { chat_id: chatId, text: reply, parse_mode: 'Markdown' });
        return;
    }

    // ── /post ──────────────────────────────────────────────────
    if (text.startsWith('/post') || text.toLowerCase() === 'post now') {
        const parts = text.split(' ');
        const postType = parts[1]; // optional: /post sales_pitch
        await telegramRequest('sendMessage', { chat_id: chatId, text: '📢 Posting to channel now...', parse_mode: 'Markdown' });
        await runChannelPost(postType);
        await telegramRequest('sendMessage', { chat_id: chatId, text: '✅ Post sent to channel.', parse_mode: 'Markdown' });
        return;
    }

    // ── /help ──────────────────────────────────────────────────
    if (text.startsWith('/help') || text.startsWith('/start')) {
        const helpMsg =
            `🤖 *ARIA — AviSignals Admin Bot*\n\n` +
            `*QUICK COMMANDS*\n` +
            `• /status — live metrics\n` +
            `• /briefing — full business briefing\n` +
            `• /revenue — revenue snapshot\n` +
            `• /users — user count + today's signups\n` +
            `• /giveaway — run a code giveaway NOW\n` +
            `• /countdown — start live session countdown NOW\n` +
            `• /post — random channel broadcast NOW\n` +
            `• /broadcast [msg] — post custom message to channel\n\n` +
            `*OR* just ask me anything in plain English!\n` +
            `_e.g. "what should I focus on today?" or "write a win post"_`;
        await telegramRequest('sendMessage', { chat_id: chatId, text: helpMsg, parse_mode: 'Markdown' });
        return;
    }

    // For everything else — pass to AI with live context injected
    try {
        const ctx = await fetchLiveContext();

        const contextBlock = `\nLIVE BUSINESS DATA (as of ${new Date().toLocaleTimeString('en-KE', { timeZone: 'Africa/Nairobi' })}):\n` +
            Object.entries(ctx).map(([k, v]) => `- ${k}: ${v}`).join('\n');

        const completion = await groq.chat.completions.create({
            messages: [
                { role: 'system', content: ADMIN_SYSTEM_PROMPT + contextBlock },
                { role: 'user', content: text }
            ],
            model: 'llama-3.3-70b-versatile',
            temperature: 0.6,
            max_tokens: 600
        });

        const reply = completion.choices[0]?.message?.content?.trim()
            || 'Sorry, I had trouble generating a response. Try again.';

        await telegramRequest('sendMessage', {
            chat_id: chatId,
            text: reply,
            parse_mode: 'Markdown'
        });

    } catch (err) {
        console.error('❌ Admin bot AI error:', err.message);
        await telegramRequest('sendMessage', {
            chat_id: chatId,
            text: '⚠️ I had an error processing that. Try again in a moment.',
            parse_mode: 'Markdown'
        });
    }
}

// ─── Long polling loop ────────────────────────────────────────
let pollingActive = false;

async function pollForAdminMessages() {
    if (!BOT_TOKEN || !ADMIN_CHAT) return;
    if (pollingActive) return;
    pollingActive = true;

    console.log('👂 Admin bot polling started...');

    const poll = async () => {
        try {
            const res = await telegramRequest('getUpdates', {
                offset: lastUpdateId + 1,
                timeout: 30,   // long poll — waits up to 30s for a message
                allowed_updates: ['message']
            });

            if (res?.ok && res.result?.length) {
                for (const update of res.result) {
                    lastUpdateId = update.update_id;
                    if (update.message) {
                        await handleAdminMessage(update.message);
                    }
                }
            }
        } catch (err) {
            console.error('❌ Polling error:', err.message);
            await new Promise(r => setTimeout(r, 5000)); // back off on error
        }

        if (pollingActive) {
            setImmediate(poll); // tight loop — processes messages as fast as they arrive
        }
    };

    poll();
}

function stopPolling() {
    pollingActive = false;
    console.log('🛑 Admin bot polling stopped.');
}

// ============================================================
// STARTUP
// ============================================================
function startTelegramAgent() {
    console.log('🚀 AviSignals Telegram Agent v3 — Initializing...');

    // ── Channel content broadcast: 2x per hour (:15, :45), 6am–11pm ──
    cron.schedule('15,45 6-23 * * *', runChannelPost);

    // ── Daily Admin Briefings (EAT timezone = UTC+3) ──────────────────
    // 🌅 Morning briefing: 7:00 AM EAT = 04:00 UTC
    cron.schedule('0 4 * * *', () => sendAdminBriefing('🌅 Morning'));
    // ☀️ Midday briefing:  12:00 PM EAT = 09:00 UTC
    cron.schedule('0 9 * * *', () => sendAdminBriefing('☀️ Midday'));
    // 🌙 Night briefing:    9:00 PM EAT = 18:00 UTC
    cron.schedule('0 18 * * *', () => sendAdminBriefing('🌙 Night'));

    // ── Start admin bot polling ────────────────────────────────────────
    pollForAdminMessages();

    // ── Initialize Marketing Bot (countdowns + giveaways) ─────────────
    const TelegramMarketingBot = require('../marketing/telegramMarketing');
    const marketingBot = new TelegramMarketingBot();
    global.marketingBotInstance = marketingBot; // expose for admin commands
    marketingBot.start();

    console.log('✅ Telegram Agent v3 ready:');
    console.log('   📢 Channel broadcast  — 2x/hour (:15, :45) 6am–11pm EAT');
    console.log('   📋 Admin briefings    — 7AM, 12PM, 9PM EAT (no hourly spam)');
    console.log('   🎁 Code giveaway      — 1:00 PM EAT daily');
    console.log('   🔴 Live countdown     — 6:30→7:00 PM EAT daily');
    console.log('   👂 Admin bot polling  — always on');
    console.log(`   💬 Admin chat ID      — ${ADMIN_CHAT || 'NOT SET'}`);
    console.log(`   📣 Channel            — ${CHANNEL_ID}`);
}

module.exports = {
    startTelegramAgent,
    runChannelPost,
    sendToAdmin,
    sendToChannel,
    stopPolling
};
